name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or whatever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn run build:demo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./build # directory to deploy

      - name: Store Google Maps API key as GitHub Secret
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.actions.createOrUpdateRepoSecret({
              owner: context.repo.owner,
              repo: context.repo.repo,
              secret_name: 'REACT_APP_GOOGLE_MAPS_API_KEY',
              secret_value: '${{ secrets.GOOGLE_MAPS_API_KEY }}'
            })
          token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
